// Do not include this file except in pinmux_stm32l4.c, as it contains an array definition
#include "pinmux/pinmux.h"
#include "pinmux/pinmux_stm32l4.h"

static const pinmux_cfg_t pins[] =
{
  {
    // PB_SEL - power on button - WKUP1
    .pin = (PINMUX_PA | 0),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_INTERRUPT_FALLING | PINMUX_SPEED_LOW)
  },
  {
    // PWM - TIM2 CHANNEL 2
    .pin = (PINMUX_PA | 1),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_1 | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_LOW | PINMUX_SPEED_LOW)
  },
  {
    // BUZZER_PWM - TIM5 CHANNEL 3
    .pin = (PINMUX_PA | 2),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_2 | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_LOW | PINMUX_SPEED_LOW)
  },
  {
    // ANALOG_SPARE - ADC12 CHANNEL 8
    .pin = (PINMUX_PA | 3),
    .flags = (PINMUX_MODE_ANALOG | PINMUX_SPEED_LOW)
  },
  {
    // SPI1_FPGA_CS
    .pin = (PINMUX_PA | 4),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_5 | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_HIGH | PINMUX_SPEED_LOW)
  },
  {
    // SPI1_SCLK
    .pin = (PINMUX_PA | 5),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_5 | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_HIGH | PINMUX_SPEED_HIGH)
  },
  {
    // SPI1_MISO
    .pin = (PINMUX_PA | 6),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_5 | PINMUX_OUT_MODE_OPEN_DRAIN | PINMUX_PULL_UP | PINMUX_SPEED_HIGH)
  },
  {
    // SPI1_MOSI
    .pin = (PINMUX_PA | 7),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_5 | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_HIGH | PINMUX_SPEED_HIGH)
  },
  {
    // SW_BACKUP
    .pin = (PINMUX_PA | 8),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_INTERRUPT_FALLING | PINMUX_SPEED_LOW)
  },
  {
    // USART1_TX
    .pin = (PINMUX_PA | 9),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_7 | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_HIGH | PINMUX_PULL_UP | PINMUX_SPEED_HIGH)
  },
  {
    // USART1_RX
    .pin = (PINMUX_PA | 10),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_7 | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_HIGH | PINMUX_PULL_UP | PINMUX_SPEED_HIGH)
  },
  {
    // USB_DM
    .pin = (PINMUX_PA | 11),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_10 | PINMUX_OUT_MODE_OPEN_DRAIN | PINMUX_PULL_NO | PINMUX_SPEED_HIGH)
  },
  {
    // USB_DP
    .pin = (PINMUX_PA | 12),
    .flags = (PINMUX_MODE_ALTERNATE | PINMUX_ALT_FUNCTION_10 | PINMUX_OUT_MODE_OPEN_DRAIN | PINMUX_PULL_NO | PINMUX_SPEED_HIGH)
  },
  // PA13 - JTMS-SWDIO
  // PA14 - JTCK-SWDCLK
  // PA15 - JTDI-SWDIO
  // PB0 - NC
  {
    // FPGA_READY
    .pin = (PINMUX_PB | 1),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_INTERRUPT_FALLING | PINMUX_SPEED_LOW)
  },
  // PB2 - NC
  // PB3 - JTDO-TRACESWO
  // PB4 - NC
  // PB5 - NC
  // PB6 - NC
  // PB7 - NC
  {
    // PB_MUTE
    .pin = (PINMUX_PB | 8),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_SPEED_LOW)
  },
  {
    // PB_PLUS
    .pin = (PINMUX_PB | 9),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_SPEED_LOW)
  },
  {
    // PB_MINUS
    .pin = (PINMUX_PB | 10),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_SPEED_LOW)
  },
  // PB11 - NC
  {
    // MOTOR_IN_A
    .pin = (PINMUX_PB | 12),
    .flags = (PINMUX_MODE_OUTPUT | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_LOW | PINMUX_SPEED_LOW)
  },
  {
    // MOTOR_IN_B
    .pin = (PINMUX_PB | 13),
    .flags = (PINMUX_MODE_OUTPUT | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_LOW | PINMUX_SPEED_LOW)
  },
  {
    // CE_CONTROL
    .pin = (PINMUX_PB | 14),
    .flags = (PINMUX_MODE_OUTPUT | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_LOW | PINMUX_SPEED_LOW)
  },
  {
    // PGOOD
    .pin = (PINMUX_PB | 15),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_SPEED_LOW)
  },
  {
    // SOUNDER_CURRENT - ADC123 CHANNEL 1
    .pin = (PINMUX_PC | 0),
    .flags = (PINMUX_MODE_ANALOG | PINMUX_SPEED_LOW)
  },
  {
    // MOTOR_CURRENT - ADC123 CHANNEL 2
    .pin = (PINMUX_PC | 1),
    .flags = (PINMUX_MODE_ANALOG | PINMUX_SPEED_LOW)
  },
  {
    // VBATT_SCALED - ADC123 CHANNEL 3
    .pin = (PINMUX_PC | 2),
    .flags = (PINMUX_MODE_ANALOG | PINMUX_SPEED_LOW)
  },
  // PC3 - NC
  // PC4 - NC
  {
    // nMOTOR_FAULT_B
    .pin = (PINMUX_PC | 5),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_INTERRUPT_FALLING | PINMUX_SPEED_LOW)
  },
  {
    // nMOTOR_FAULT_A
    .pin = (PINMUX_PC | 6),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_INTERRUPT_FALLING | PINMUX_SPEED_LOW)
  },
  {
    // LDO_EN
    .pin = (PINMUX_PC | 7),
    .flags = (PINMUX_MODE_OUTPUT | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_LOW | PINMUX_SPEED_LOW)
  },
  {
    // SW_END
    .pin = (PINMUX_PC | 8),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_INTERRUPT_FALLING | PINMUX_SPEED_LOW)
  },
  {
    // SW_HOME
    .pin = (PINMUX_PC | 9),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_INTERRUPT_FALLING | PINMUX_SPEED_LOW)
  },
  {
    // PWR_UP
    .pin = (PINMUX_PC | 10),
    .flags = (PINMUX_MODE_OUTPUT | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_LOW | PINMUX_SPEED_LOW)
  },
  {
    // nPRESSURE_PATIENT_ALERT
    .pin = (PINMUX_PC | 11),
    .flags = (PINMUX_MODE_INPUT | PINMUX_PULL_UP | PINMUX_INTERRUPT_FALLING | PINMUX_SPEED_LOW)
  },
  // PC12 - NC
  // PC13 - NC
  // PC14 - NC
  {
    // BATTERY_PRESENT_LED
    .pin = (PINMUX_PC | 15),
    .flags = (PINMUX_MODE_OUTPUT | PINMUX_OUT_MODE_PUSH_PULL | PINMUX_INITIAL_OUT_VAL_LOW | PINMUX_SPEED_LOW)
  },
};
