#ifndef VENTILATION_STATES_H
#define VENTILATION_STATES_H

enum ventilation_state
{
  VENTILATION_STATE_HOMING,
  VENTILATION_STATE_IDLE,
  VENTILATION_STATE_INHALE,
  VENTILATION_STATE_INHALE_PAUSE,
  VENTILATION_STATE_EXHALE,
  VENTILATION_STATE_EXHALE_PAUSE,
  VENTILATION_STATE_FAULT,
  VENTILATION_STATE_MAINTENANCE,
  VENTILATION_STATE_UNRECOVERABLE,

  VENTILATION_STATE_COUNT // Not a valid state
};

#endif /* VENTILATION_STATES_H */
