#ifndef EVENT_H
#define EVENT_H

typedef enum
{
  EV_NONE,
  EV_DO_FLOW_READ,
  EV_DO_PRESSURE_READ,
  EV_DO_VBATT_READ,
  EV_DO_MOTOR_CURR_READ,
  EV_DO_TEMP_READ,
  EV_FLOW_READ_COMPLETE,
  EV_PRESSURE_READ_COMPLETE,
  EV_VBATT_READ_COMPLETE,
  EV_MOTOR_CURR_READ_COMPLETE,
  EV_TEMP_READ_COMPLETE,
  EV_TIMER_COMPLETE,
  EV_GPIO_ALERTS,
  EV_GPIO_SWITCHES,
  EV_CASE_INTLK_ALERT,
  EV_CASE_INTLK_ALERT_CLEAR,
  EV_PRESSURE_ALERT,
  EV_PRESSURE_ALERT_CLEAR,
  EV_FLOW_ALERT,
  EV_FLOW_ALERT_CLEAR,
  EV_VBATT_ALERT,
  EV_VBATT_ALERT_CLEAR,
  EV_GPIO_SWITCH_0,
  EV_GPIO_SWITCH_1,
  EV_GPIO_SWITCH_2,
  EV_GPIO_SWITCH_3,
  EV_DO_UPDATE_DISPLAY_0,
  EV_DO_UPDATE_DISPLAY_1,
  EV_DO_UART_LOG,

  /* SYSTEM TEST */
  EV_UART_EV_INJECT,
  EV_UART_EV_DISPLAY_0_WRITE,
  EV_UART_EV_DISPLAY_1_WRITE
} event_t;

#endif /* EVENT_H */
